name: ci

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches: main

permissions:
  contents: write

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Podman
        run: make build
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: out/*.deb
          retention-days: 7

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download package
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: out/
      - name: List
        run: ls -lha

  release:
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: out/*.deb
